from django.db import models
from django.contrib.auth.models import User

class Tabla(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='user',
        default=True,
        null=True
    )
    documentos_institucionales = models.CharField(max_length=50, blank=True, null=True)
    finanzas = models.CharField(max_length=50, blank=True, null=True)
    servicios_bancarios = models.CharField(max_length=50, blank=True, null=True)
    rrhh = models.CharField(max_length=50, blank=True, null=True)
    directorio_de_contactos = models.CharField(max_length=50, blank=True, null=True)
    productos_institucionales = models.CharField(max_length=50, blank=True, null=True)
    correo_electrónico = models.EmailField(max_length=50, blank=True, null=True)
    bases_de_datos_internos = models.CharField(max_length=50, blank=True, null=True)
    bases_de_datos_externos = models.CharField(max_length=50, blank=True, null=True)
    bases_de_datos_colaborativos = models.CharField(max_length=50, blank=True, null=True)
    pagina_web_interna = models.CharField(max_length=50, blank=True, null=True)
    pagina_web_externa = models.CharField(max_length=50, blank=True, null=True)
    respaldos = models.CharField(max_length=50, blank=True, null=True)
    infraestructura = models.CharField(max_length=50, blank=True, null=True)
    informatica = models.CharField(max_length=50, blank=True, null=True)
    base_de_datos_de_contrasenas = models.CharField(max_length=50, blank=True, null=True)
    datos_e_informacion_no_institucionales = models.CharField(max_length=50, blank=True, null=True)
    navegacion_en_internet = models.CharField(max_length=50, blank=True, null=True)
    chat_interno = models.CharField(max_length=50, blank=True, null=True)
    chat_externo = models.CharField(max_length=50, blank=True, null=True)
    llamadas_telefonicas_internas = models.CharField(max_length=50, blank=True, null=True)
    llamadas_telefonicas_externas = models.CharField(max_length=50, blank=True, null=True)
    allanamiento = models.CharField(max_length=50, blank=True, null=True)
    persecucion = models.CharField(max_length=50, blank=True, null=True)
    orden_de_secuestro_detencion = models.CharField(max_length=50, blank=True, null=True)
    sabotaje_ataque_fisico_electronico = models.CharField(max_length=50, blank=True, null=True)
    daños_por_vandalismo = models.CharField(max_length=50, blank=True, null=True)
    extorsion = models.CharField(max_length=50, blank=True, null=True)
    fraude = models.CharField(max_length=50, blank=True, null=True)
    robo = models.CharField(max_length=50, blank=True, null=True)
    hurto_de_informacion_electronica = models.CharField(max_length=50, blank=True, null=True)
    intrusion_a_red_interna = models.CharField(max_length=50, blank=True, null=True)
    infiltracion = models.CharField(max_length=50, blank=True, null=True)
    virus_ejecucion_no_autorizado_de_programas = models.CharField(max_length=50, blank=True, null=True)
    violacion_a_derechos_de_autor = models.CharField(max_length=50, blank=True, null=True)
    incendio = models.CharField(max_length=50, blank=True, null=True)
    inundacion_deslave = models.CharField(max_length=50, blank=True, null=True)
    sismo = models.CharField(max_length=50, blank=True, null=True)
    polvo = models.CharField(max_length=50, blank=True, null=True)
    falta_de_ventilacion = models.CharField(max_length=50, blank=True, null=True)
    electromagnetismo = models.CharField(max_length=50, blank=True, null=True)
    sobrecarga_electrica = models.CharField(max_length=50, blank=True, null=True)
    falla_de_corriente_apagones = models.CharField(max_length=50, blank=True, null=True)
    falla_dano_disco_duro = models.CharField(max_length=50, blank=True, null=True)
    falta_de_induccion_capacitacion_sensibilizacion_riesgos = models.CharField(max_length=50, blank=True, null=True)
    mal_manejo_de_sistemas_herramientas = models.CharField(max_length=50, blank=True, null=True)
    utilizacion_de_programas_no_autorizados = models.CharField(max_length=50, blank=True, null=True)
    falta_de_pruebas_de_software = models.CharField(max_length=50, blank=True, null=True)
    perdida_de_datos = models.CharField(max_length=50, blank=True, null=True)
    infeccion_de_sistemas_unidades_portables_sin_escaneo = models.CharField(max_length=50, blank=True, null=True)
    manejo_inadecuado_de_datos_criticos = models.CharField(max_length=50, blank=True, null=True)
    unidades_portables_con_informacion_sin_cifrado = models.CharField(max_length=50, blank=True, null=True)
    transmision_no_cifrada_de_datos_criticos = models.CharField(max_length=50, blank=True, null=True)
    manejo_inadecuado_de_contrasenas = models.CharField(max_length=50, blank=True, null=True)
    compartir_contrasenas_permisos_terceros_no_autorizados = models.CharField(max_length=50, blank=True, null=True)
    transmision_de_contrasenas_por_telefono = models.CharField(max_length=50, blank=True, null=True)
    exposicion_o_extravio_de_equipo = models.CharField(max_length=50, blank=True, null=True)
    sobrepasar_autoridades = models.CharField(max_length=50, blank=True, null=True)
    falta_de_definicion_de_perfil = models.CharField(max_length=50, blank=True, null=True)
    falta_de_mantenimiento_fisico = models.CharField(max_length=50, blank=True, null=True)
    falta_de_actualizacion_de_software = models.CharField(max_length=50, blank=True, null=True)
    fallas_en_permisos_de_usuarios = models.CharField(max_length=50, blank=True, null=True)
    acceso_electronico_no_autorizado_sistemas_externos = models.CharField(max_length=50, blank=True, null=True)
    acceso_electronico_no_autorizado_sistemas_internos = models.CharField(max_length=50, blank=True, null=True)
    red_cableada_expuesta_para_el_acceso_no_autorizado = models.CharField(max_length=50, blank=True, null=True)
    red_inalambrica_expuesta_al_acceso_no_autorizado = models.CharField(max_length=50, blank=True, null=True)
    dependencia_a_servicio_tecnico_externo = models.CharField(max_length=50, blank=True, null=True)
    falta_de_normas_y_reglas_claras = models.CharField(max_length=50, blank=True, null=True)
    falta_de_mecanismos_de_verificacion_de_normas_y_reglas = models.CharField(max_length=50, blank=True, null=True)
    ausencia_de_documentacion = models.CharField(max_length=50, blank=True, null=True)


    class Meta:
        ordering = ['id']
