# Generated by Django 4.1.3 on 2022-12-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_tabla_delete_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla',
            name='Acceso_electronico_no_autorizado_sistemas_internos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='acceso_electronico_no_autorizado_sistemas_externos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='allanamiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='ausencia_de_documentacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='compartir_contrasenas_permisos_terceros_no_autorizados',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='daños_por_vandalismo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='dependencia_a_servicio_tecnico_externo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='electromagnetismo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='exposicion_o_extravio_de_equipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='extorsion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='falla_dano_disco_duro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='falla_de_corriente_apagones',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='fallas_en_permisos_de_usuarios',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='falta_de_actualizacion_de_software',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='falta_de_definicion_de_perfil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='falta_de_induccion_capacitacion_sensibilizacion_riesgos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='falta_de_mantenimiento_fisico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='falta_de_mecanismos_de_verificacion_de_normas_y_reglas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='falta_de_normas_y_reglas_claras',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='falta_de_pruebas_de_software',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='falta_de_ventilacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='fraude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='hurto_de_informacion_electronica',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='incendio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='infeccion_de_sistemas_unidades_portables_sin_escaneo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='infiltracion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='intrusion_a_red_interna',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='inundacion_deslave',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='mal_manejo_de_sistemas_herramientas',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='manejo_inadecuado_de_contrasenas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='manejo_inadecuado_de_datos_criticos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='orden_de_secuestro_detencion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='perdida_de_datos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='persecucion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='polvo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='red_cableada_expuesta_para_el_acceso_no_autorizado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='red_inalambrica_expuesta_al_acceso_no_autorizado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='robo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sabotaje_ataque_fisico_electronico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sismo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sobrecarga_electrica',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sobrepasar_autoridades',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='transmision_de_contrasenas_por_telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='transmision_no_cifrada_de_datos_criticos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='unidades_portables_con_informacion_sin_cifrado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='utilizacion_de_programas_no_autorizados',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='violacion_a_derechos_de_autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='virus_ejecucion_no_autorizado_de_programas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
